export type Locale = "en" | "hi" | "ur";

const hi: Record<string, string> = {
  "nav.packages":"पैकेज","nav.how":"यह कैसे काम करता है","nav.about":"हमारे बारे में","nav.dashboard":"मेरा डैशबोर्ड","nav.begin":"अपनी यात्रा शुरू करें",
  "hero.eyebrow":"नीयत से बनाई गई यात्राएँ","hero.title1":"आपकी पवित्र यात्रा,","hero.title2":"खूबसूरती से नियोजित।","hero.copy":"पहली नमाज़ से अंतिम विदाई तक, अलसफ़र हर विवरण का ध्यान रखता है—ताकि आप उस पर ध्यान दे सकें जो वास्तव में महत्वपूर्ण है।","hero.explore":"पैकेज देखें","hero.trusted":"विश्वसनीय व्यवस्थाएँ","hero.care":"24/7 यात्री सहायता","hero.served":"सेवा प्राप्त यात्री","hero.lifetime":"जीवनभर की यादगार यात्राएँ",
  "packages.find":"अपनी यात्रा खोजें","packages.heading":"हर यात्री के लिए बनाया गया","packages.copy":"पारदर्शी मूल्य, सावधानी से चुने गए होटल और आपकी यात्रा का महत्व समझने वाले लोग।","packages.loved":"सबसे लोकप्रिय","packages.days":"सुकून भरे दिन","packages.meals":"रोज़ नाश्ता और रात का खाना","packages.view":"विवरण देखें","packages.person":"प्रति व्यक्ति",
  "journey.simple":"सरल और सहयोगपूर्ण","journey.heading":"नीयत से आगमन तक","journey.choose":"अपना पैकेज चुनें","journey.chooseCopy":"अवधि, ठहरने और सेवाओं की तुलना कर सही यात्रा चुनें।","journey.share":"अपना विवरण साझा करें","journey.shareCopy":"सुरक्षित रूप से आरक्षित करें और हमारी टीम को आपकी यात्रा आवश्यकताओं की समीक्षा करने दें।","journey.travel":"सुकून से यात्रा करें","journey.travelCopy":"आपका स्थानीय गाइड और सहायता टीम हर महत्वपूर्ण कदम पर आपके साथ रहती है।","journey.waiting":"एक खूबसूरत यात्रा आपका इंतज़ार कर रही है।","journey.speak":"आज ही हमारी यात्री सहायता टीम से बात करें।","journey.plan":"मेरी यात्रा की योजना बनाएँ",
  "footer.copy":"भारतीय यात्रियों को आस्था, आराम और सुकून की यात्रा की ओर मार्गदर्शन।","footer.explore":"देखें","footer.traveler":"यात्री लॉगिन","footer.guide":"गाइड लॉगिन","footer.support":"सहायता","footer.hours":"सोम–शनि, सुबह 9–शाम 7","footer.created":"रचनाकार","footer.founder":"अलसफ़र के संस्थापक","footer.made":"© 2026 अलसफ़र ट्रैवल सर्विसेज़। शेख रेहान द्वारा प्यार से बनाया गया।",
  "common.traveler":"यात्री","common.guide":"स्थानीय गाइड","common.or":"या","common.days":"दिन","common.back":"वापस","common.package":"पैकेज","common.payment":"भुगतान","common.documents":"दस्तावेज़","common.close":"बंद करें",
  "auth.traveler":"मैं यात्री हूँ","auth.guide":"मैं स्थानीय गाइड हूँ","auth.email":"ईमेल पता","auth.password":"पासवर्ड","auth.google":"Google से जारी रखें","auth.googleTraveler":"Google से यात्री के रूप में साइन अप करें","auth.googleGuide":"Google से गाइड के रूप में साइन अप करें",
  "login.welcome":"अलसफ़र में आपका स्वागत है","login.peace":"अस्सलामु अलैकुम।","login.copy":"अपनी पवित्र यात्रा सँभालने के लिए साइन इन करें।","login.submit":"डैशबोर्ड पर जाएँ","login.pending":"साइन इन हो रहा है…","login.new":"अलसफ़र पर नए हैं?","login.create":"खाता बनाएँ","login.art":"दिल की यात्रा","login.artTitle":"हर कदम,\nपूरी देखभाल के साथ।","login.artCopy":"अपना कार्यक्रम, दस्तावेज़, गाइड विवरण और अपडेट एक ही जगह पाएँ।",
  "signup.join":"अलसफ़र से जुड़ें","signup.title":"अपना खाता बनाएँ।","signup.copy":"चुनें कि आप अलसफ़र का उपयोग कैसे करेंगे, फिर अपना विवरण भरें।","signup.name":"पूरा नाम","signup.namePlaceholder":"आपका पूरा नाम","signup.confirm":"पासवर्ड की पुष्टि करें","signup.confirmPlaceholder":"वही पासवर्ड दोबारा लिखें","signup.submit":"खाता बनाएँ","signup.pending":"खाता बन रहा है…","signup.existing":"पहले से खाता है?","signup.signin":"साइन इन करें","signup.guideNote":"आप स्थानीय गाइड के रूप में पंजीकरण कर रहे हैं। आपका डैशबोर्ड और अनुमतियाँ गाइड भूमिका के अनुसार होंगी।","signup.art":"आपकी यात्रा यहाँ से शुरू होती है","signup.artTitle":"आस्था के साथ यात्रा,\nदेखभाल के साथ मार्गदर्शन।","signup.artCopy":"पैकेज, बुकिंग और यात्रा विवरण एक जगह सँभालने के लिए सुरक्षित खाता बनाएँ।",
  "detail.tier":"पैकेज","detail.per":"प्रति यात्री","detail.book":"यह पैकेज बुक करें","detail.duration":"यात्रा अवधि","detail.accommodation":"ठहरने की व्यवस्था","detail.distance":"दूरी","detail.meals":"भोजन","detail.mealsYes":"नाश्ता और रात का खाना शामिल","detail.mealsNo":"अलग से उपलब्ध","detail.included":"क्या शामिल है","detail.supported":"शुरू से अंत तक सहयोगपूर्ण यात्रा","detail.review":"भुगतान से पहले हमारी टीम आपके दस्तावेज़ों और उपलब्धता की समीक्षा करके आपसे संपर्क करेगी।","detail.visa":"वीज़ा प्रक्रिया में सहायता","detail.transfer":"हवाई अड्डा और शहरों के बीच स्थानांतरण","detail.ziyarat":"मार्गदर्शित ज़ियारत व्यवस्था","detail.guide":"स्थानीय गाइड और यात्री सहायता","detail.orientation":"यात्रा-पूर्व मार्गदर्शन","detail.ready":"अपनी जगह आरक्षित करने के लिए तैयार हैं?","detail.readyCopy":"यात्रा विवरण भरें, आवश्यक पहचान दस्तावेज़ अपलोड करें और कार्यालय में भुगतान चुनें।","detail.bookNow":"अभी बुक करें",
  "pkg.essential-umrah.name":"आवश्यक उमराह","pkg.essential-umrah.description":"सभी आवश्यक तीर्थ व्यवस्थाओं के साथ एक सुविचारित और किफ़ायती यात्रा।","pkg.essential-umrah.hotel":"आरामदायक 3-सितारा ठहराव","pkg.essential-umrah.distance":"हरम से 900 मीटर",
  "pkg.serene-journey.name":"सुकून भरी यात्रा","pkg.serene-journey.description":"पूरी यात्रा में संतुलित आराम, मार्गदर्शित ज़ियारत और सुव्यवस्थित स्थानांतरण।","pkg.serene-journey.hotel":"प्रीमियम 4-सितारा ठहराव","pkg.serene-journey.distance":"हरम से 550 मीटर",
  "pkg.royal-pilgrimage.name":"शाही तीर्थयात्रा","pkg.royal-pilgrimage.description":"उत्कृष्ट होटलों और निजी मार्गदर्शन के साथ एक विशेष आध्यात्मिक अनुभव।","pkg.royal-pilgrimage.hotel":"लक्ज़री 5-सितारा ठहराव","pkg.royal-pilgrimage.distance":"हरम से 250 मीटर",
  "pkg.signature-alsafar.name":"सिग्नेचर अलसफ़र","pkg.signature-alsafar.description":"सुइट, कंसीयर्ज और निजी परिवहन के साथ हमारी सर्वोत्तम घर-से-घर तक यात्रा।","pkg.signature-alsafar.hotel":"काबा-दृश्य वाला 5-सितारा सुइट","pkg.signature-alsafar.distance":"हरम से कुछ कदम",
  "booking.book":"बुक करें","booking.complete":"अपनी बुकिंग पूरी करें","booking.journey":"यात्रा","booking.documents":"दस्तावेज़","booking.payment":"भुगतान","booking.details":"आपकी यात्रा का विवरण","booking.detailsCopy":"बताएँ कि आप कब यात्रा करना चाहते हैं और हमारी टीम आपसे कैसे संपर्क करे।","booking.date":"पसंदीदा प्रस्थान तिथि","booking.travelers":"यात्रियों की संख्या","booking.traveler":"यात्री","booking.phone":"फ़ोन / WhatsApp नंबर","booking.toDocuments":"दस्तावेज़ों पर जाएँ","booking.identity":"पहचान दस्तावेज़","booking.uploadCopy":"स्पष्ट PDF, JPG या PNG प्रतियाँ अपलोड करें। प्रत्येक फ़ाइल 2 MB से छोटी होनी चाहिए।","booking.passportNo":"पासपोर्ट नंबर","booking.passport":"पासपोर्ट दस्तावेज़","booking.aadhaarNo":"आधार नंबर","booking.aadhaar":"आधार कार्ड","booking.panNo":"PAN नंबर","booking.pan":"PAN कार्ड","booking.toPayment":"भुगतान पर जाएँ","booking.method":"भुगतान का तरीका","booking.methodCopy":"ऑनलाइन भुगतान बाद में जोड़ा जाएगा। अभी पैकेज आरक्षित करें और कार्यालय द्वारा दस्तावेज़ों की पुष्टि के बाद भुगतान करें।","booking.office":"कार्यालय में भुगतान","booking.officeCopy":"पुष्टि के बाद अलसफ़र कार्यालय में नकद भुगतान करें।","booking.pendingNote":"हमारी टीम दस्तावेज़ों की समीक्षा करके आपसे संपर्क करे तब तक बुकिंग लंबित रहेगी।","booking.creating":"बुकिंग बन रही है…","booking.confirm":"बुकिंग की पुष्टि करें","booking.duration":"अवधि","booking.total":"अनुमानित कुल","booking.due":"दस्तावेज़ समीक्षा और पुष्टि के बाद अलसफ़र कार्यालय में भुगतान देय होगा।",
  "confirm.received":"बुकिंग प्राप्त हुई","confirm.title":"आपका यात्रा अनुरोध हमारे पास पहुँच गया है।","confirm.copy":"अलहम्दुलिल्लाह, आपके दस्तावेज़ और बुकिंग विवरण सफलतापूर्वक जमा हो गए। हमारी टीम भुगतान से पहले उनकी समीक्षा करके आपसे संपर्क करेगी।","confirm.reference":"बुकिंग संदर्भ","confirm.travelersTotal":"यात्री और कुल राशि","confirm.office":"कार्यालय में भुगतान","confirm.warning":"अधिकृत अलसफ़र प्रतिनिधि की पुष्टि से पहले किसी को भुगतान न करें।","confirm.dashboard":"मेरे डैशबोर्ड पर जाएँ",
  "dashboard.logout":"लॉग आउट","dashboard.guide":"गाइड कार्यक्षेत्र","dashboard.traveler":"यात्री डैशबोर्ड","dashboard.greeting":"अस्सलामु अलैकुम","dashboard.guideCopy":"यहाँ वे यात्री हैं जिनकी यात्रा में आप सहायता कर रहे हैं।","dashboard.travelerCopy":"आपकी तीर्थयात्रा की हर चीज़ एक ही जगह।","dashboard.assignments":"कार्य देखें","dashboard.explore":"पैकेज देखें","dashboard.assigned":"निर्धारित यात्री","dashboard.nextGroup":"अगला समूह","dashboard.messages":"संदेश","dashboard.upcoming":"आगामी यात्राएँ","dashboard.docsReady":"तैयार दस्तावेज़","dashboard.daysDeparture":"प्रस्थान में दिन","dashboard.groups":"आगामी समूह","dashboard.yourJourney":"आपकी यात्रा","dashboard.confirmed":"पुष्टि हुई","dashboard.ready":"तैयार","dashboard.briefing":"प्रस्थान-पूर्व बैठक","dashboard.orientation":"प्रस्थान-पूर्व मार्गदर्शन","dashboard.scheduled":"निर्धारित","dashboard.guideProfile":"प्रमाणित स्थानीय गाइड","dashboard.travelerProfile":"पंजीकृत यात्री","dashboard.documents":"दस्तावेज़","dashboard.support":"सहायता संदेश","dashboard.profile":"प्रोफ़ाइल सेटिंग",
  "language.label":"भाषा"
};

const ur: Record<string, string> = {
  "nav.packages":"پیکیجز","nav.how":"یہ کیسے کام کرتا ہے","nav.about":"ہمارے بارے میں","nav.dashboard":"میرا ڈیش بورڈ","nav.begin":"اپنا سفر شروع کریں",
  "hero.eyebrow":"نیت سے ترتیب دیے گئے سفر","hero.title1":"آپ کا مقدس سفر،","hero.title2":"خوبصورتی سے منصوبہ بند۔","hero.copy":"پہلی نماز سے آخری الوداع تک، السفر ہر تفصیل کا خیال رکھتا ہے—تاکہ آپ اصل مقصد پر توجہ دے سکیں۔","hero.explore":"پیکیجز دیکھیں","hero.trusted":"قابلِ اعتماد انتظامات","hero.care":"24/7 زائرین کی مدد","hero.served":"خدمت پانے والے زائرین","hero.lifetime":"زندگی بھر یاد رہنے والے سفر",
  "packages.find":"اپنا سفر تلاش کریں","packages.heading":"ہر زائر کے لیے بنایا گیا","packages.copy":"شفاف قیمتیں، احتیاط سے منتخب ہوٹل اور آپ کے سفر کی اہمیت سمجھنے والے لوگ۔","packages.loved":"سب سے مقبول","packages.days":"پُرسکون دن","packages.meals":"روزانہ ناشتہ اور رات کا کھانا","packages.view":"تفصیل دیکھیں","packages.person":"فی فرد",
  "journey.simple":"آسان اور معاون","journey.heading":"نیت سے آمد تک","journey.choose":"اپنا پیکیج منتخب کریں","journey.chooseCopy":"مدت، قیام اور خدمات کا موازنہ کرکے موزوں سفر منتخب کریں۔","journey.share":"اپنی تفصیلات دیں","journey.shareCopy":"محفوظ طریقے سے بک کریں اور ہماری ٹیم کو آپ کی سفری ضروریات کا جائزہ لینے دیں۔","journey.travel":"سکون سے سفر کریں","journey.travelCopy":"آپ کا مقامی گائیڈ اور معاون ٹیم ہر اہم مرحلے پر آپ کے ساتھ رہتی ہے۔","journey.waiting":"ایک خوبصورت سفر آپ کا منتظر ہے۔","journey.speak":"آج ہی ہماری زائرین کی معاون ٹیم سے بات کریں۔","journey.plan":"میرے سفر کی منصوبہ بندی کریں",
  "footer.copy":"ہندوستانی زائرین کو ایمان، آرام اور سکون کے سفر کی طرف رہنمائی۔","footer.explore":"دیکھیں","footer.traveler":"زائر لاگ اِن","footer.guide":"گائیڈ لاگ اِن","footer.support":"مدد","footer.hours":"پیر–ہفتہ، صبح 9–شام 7","footer.created":"تخلیق کار","footer.founder":"السفر کے بانی","footer.made":"© 2026 السفر ٹریول سروسز۔ شیخ ریحان نے محبت سے بنایا۔",
  "common.traveler":"زائر","common.guide":"مقامی گائیڈ","common.or":"یا","common.days":"دن","common.back":"واپس","common.package":"پیکیج","common.payment":"ادائیگی","common.documents":"دستاویزات","common.close":"بند کریں",
  "auth.traveler":"میں زائر ہوں","auth.guide":"میں مقامی گائیڈ ہوں","auth.email":"ای میل پتہ","auth.password":"پاس ورڈ","auth.google":"Google کے ساتھ جاری رکھیں","auth.googleTraveler":"Google سے زائر کے طور پر سائن اپ کریں","auth.googleGuide":"Google سے گائیڈ کے طور پر سائن اپ کریں",
  "login.welcome":"السفر میں خوش آمدید","login.peace":"السلام علیکم۔","login.copy":"اپنے مقدس سفر کا انتظام کرنے کے لیے سائن اِن کریں۔","login.submit":"ڈیش بورڈ پر جائیں","login.pending":"سائن اِن ہو رہا ہے…","login.new":"السفر پر نئے ہیں؟","login.create":"اکاؤنٹ بنائیں","login.art":"دل کا سفر","login.artCopy":"اپنا پروگرام، دستاویزات، گائیڈ کی تفصیل اور اپ ڈیٹس ایک پُرسکون جگہ پر حاصل کریں۔",
  "signup.join":"السفر سے جڑیں","signup.title":"اپنا اکاؤنٹ بنائیں۔","signup.copy":"منتخب کریں کہ آپ السفر کو کیسے استعمال کریں گے، پھر اپنی تفصیلات درج کریں۔","signup.name":"پورا نام","signup.namePlaceholder":"آپ کا پورا نام","signup.confirm":"پاس ورڈ کی تصدیق","signup.confirmPlaceholder":"وہی پاس ورڈ دوبارہ درج کریں","signup.submit":"اکاؤنٹ بنائیں","signup.pending":"اکاؤنٹ بن رہا ہے…","signup.existing":"پہلے سے اکاؤنٹ ہے؟","signup.signin":"سائن اِن کریں","signup.guideNote":"آپ مقامی گائیڈ کے طور پر رجسٹر ہو رہے ہیں۔ آپ کا ڈیش بورڈ اور اجازتیں گائیڈ کے کردار کے مطابق ہوں گی۔","signup.art":"آپ کا سفر یہاں سے شروع ہوتا ہے","signup.artCopy":"پیکیجز، بکنگ اور سفری تفصیلات ایک جگہ سنبھالنے کے لیے محفوظ اکاؤنٹ بنائیں۔",
  "detail.tier":"پیکیج","detail.per":"فی زائر","detail.book":"یہ پیکیج بک کریں","detail.duration":"سفر کی مدت","detail.accommodation":"رہائش","detail.distance":"فاصلہ","detail.meals":"کھانا","detail.mealsYes":"ناشتہ اور رات کا کھانا شامل","detail.mealsNo":"الگ دستیاب","detail.included":"کیا شامل ہے","detail.supported":"آغاز سے اختتام تک معاون سفر","detail.review":"ادائیگی سے پہلے ہماری ٹیم آپ کی دستاویزات اور دستیابی کا جائزہ لے کر رابطہ کرے گی۔","detail.visa":"ویزا کارروائی میں مدد","detail.transfer":"ہوائی اڈے اور شہروں کے درمیان منتقلی","detail.ziyarat":"رہنمائی کے ساتھ زیارت","detail.guide":"مقامی گائیڈ اور زائرین کی مدد","detail.orientation":"سفر سے پہلے رہنمائی","detail.ready":"اپنی جگہ محفوظ کرنے کے لیے تیار ہیں؟","detail.readyCopy":"سفر کی تفصیل درج کریں، شناختی دستاویزات اپ لوڈ کریں اور دفتر میں ادائیگی منتخب کریں۔","detail.bookNow":"ابھی بک کریں",
  "pkg.essential-umrah.name":"ضروری عمرہ","pkg.essential-umrah.description":"تمام ضروری زیارتی انتظامات کے ساتھ ایک سوچا سمجھا اور کفایتی سفر۔","pkg.essential-umrah.hotel":"آرام دہ 3 ستارہ قیام","pkg.essential-umrah.distance":"حرم سے 900 میٹر",
  "pkg.serene-journey.name":"پُرسکون سفر","pkg.serene-journey.description":"پورے سفر میں متوازن آرام، رہنمائی کے ساتھ زیارت اور منظم منتقلی۔","pkg.serene-journey.hotel":"پریمیم 4 ستارہ قیام","pkg.serene-journey.distance":"حرم سے 550 میٹر",
  "pkg.royal-pilgrimage.name":"شاہانہ زیارت","pkg.royal-pilgrimage.description":"بہترین ہوٹلوں اور ذاتی رہنمائی کے ساتھ ایک خصوصی روحانی تجربہ۔","pkg.royal-pilgrimage.hotel":"لگژری 5 ستارہ قیام","pkg.royal-pilgrimage.distance":"حرم سے 250 میٹر",
  "pkg.signature-alsafar.name":"سگنیچر السفر","pkg.signature-alsafar.description":"سوئٹ، کنسیئرژ اور نجی نقل و حمل کے ساتھ ہمارا بہترین گھر سے گھر تک سفر۔","pkg.signature-alsafar.hotel":"کعبہ کے نظارے والا 5 ستارہ سوئٹ","pkg.signature-alsafar.distance":"حرم سے چند قدم",
  "booking.book":"بک کریں","booking.complete":"اپنی بکنگ مکمل کریں","booking.journey":"سفر","booking.documents":"دستاویزات","booking.payment":"ادائیگی","booking.details":"آپ کے سفر کی تفصیل","booking.detailsCopy":"بتائیں آپ کب سفر کرنا چاہتے ہیں اور ہماری ٹیم آپ سے کیسے رابطہ کرے۔","booking.date":"پسندیدہ روانگی کی تاریخ","booking.travelers":"زائرین کی تعداد","booking.traveler":"زائر","booking.phone":"فون / WhatsApp نمبر","booking.toDocuments":"دستاویزات پر جائیں","booking.identity":"شناختی دستاویزات","booking.uploadCopy":"واضح PDF، JPG یا PNG نقول اپ لوڈ کریں۔ ہر فائل 2 MB سے کم ہو۔","booking.passportNo":"پاسپورٹ نمبر","booking.passport":"پاسپورٹ دستاویز","booking.aadhaarNo":"آدھار نمبر","booking.aadhaar":"آدھار کارڈ","booking.panNo":"PAN نمبر","booking.pan":"PAN کارڈ","booking.toPayment":"ادائیگی پر جائیں","booking.method":"ادائیگی کا طریقہ","booking.methodCopy":"آن لائن ادائیگی بعد میں شامل ہوگی۔ ابھی پیکیج محفوظ کریں اور دفتر کی تصدیق کے بعد ادائیگی کریں۔","booking.office":"دفتر میں ادائیگی","booking.officeCopy":"تصدیق کے بعد السفر دفتر میں نقد ادائیگی کریں۔","booking.pendingNote":"ہماری ٹیم کے دستاویزات کا جائزہ لینے اور رابطہ کرنے تک بکنگ زیرِ التوا رہے گی۔","booking.creating":"بکنگ بن رہی ہے…","booking.confirm":"بکنگ کی تصدیق کریں","booking.duration":"مدت","booking.total":"تخمینی کل","booking.due":"دستاویزات کے جائزے اور تصدیق کے بعد السفر دفتر میں ادائیگی واجب ہوگی۔",
  "confirm.received":"بکنگ موصول ہوگئی","confirm.title":"آپ کی سفری درخواست ہمارے پاس پہنچ گئی ہے۔","confirm.copy":"الحمدللہ، آپ کی دستاویزات اور بکنگ کی تفصیلات کامیابی سے جمع ہوگئیں۔ ہماری ٹیم ادائیگی سے پہلے جائزہ لے کر رابطہ کرے گی۔","confirm.reference":"بکنگ حوالہ","confirm.travelersTotal":"زائرین اور کل رقم","confirm.office":"دفتر میں ادائیگی","confirm.warning":"السفر کے مجاز نمائندے کی تصدیق سے پہلے کسی کو ادائیگی نہ کریں۔","confirm.dashboard":"میرے ڈیش بورڈ پر جائیں",
  "dashboard.logout":"لاگ آؤٹ","dashboard.guide":"گائیڈ ورک اسپیس","dashboard.traveler":"زائر ڈیش بورڈ","dashboard.greeting":"السلام علیکم","dashboard.guideCopy":"یہاں وہ زائرین ہیں جن کے سفر میں آپ مدد کر رہے ہیں۔","dashboard.travelerCopy":"آپ کی زیارت کی ہر چیز ایک جگہ۔","dashboard.assignments":"ذمہ داریاں دیکھیں","dashboard.explore":"پیکیجز دیکھیں","dashboard.assigned":"تفویض کردہ زائرین","dashboard.nextGroup":"اگلا گروپ","dashboard.messages":"پیغامات","dashboard.upcoming":"آنے والے سفر","dashboard.docsReady":"تیار دستاویزات","dashboard.daysDeparture":"روانگی میں دن","dashboard.groups":"آنے والے گروپس","dashboard.yourJourney":"آپ کا سفر","dashboard.confirmed":"تصدیق شدہ","dashboard.ready":"تیار","dashboard.briefing":"روانگی سے پہلے میٹنگ","dashboard.orientation":"روانگی سے پہلے رہنمائی","dashboard.scheduled":"طے شدہ","dashboard.guideProfile":"تصدیق شدہ مقامی گائیڈ","dashboard.travelerProfile":"رجسٹرڈ زائر","dashboard.documents":"دستاویزات","dashboard.support":"مدد کے پیغامات","dashboard.profile":"پروفائل سیٹنگز",
  "language.label":"زبان"
};

export function translate(locale: Locale, key: string, fallback: string) {
  return locale === "hi" ? hi[key] ?? fallback : locale === "ur" ? ur[key] ?? fallback : fallback;
}

export function localize(locale: Locale, en: string, hiText: string, urText: string) {
  return locale === "hi" ? hiText : locale === "ur" ? urText : en;
}

export function packageTranslation(locale: Locale, slug: string, field: "name" | "description" | "hotel" | "distance", fallback: string) {
  return translate(locale, `pkg.${slug}.${field}`, fallback);
}

export function packageTier(locale:Locale,tier:"Basic"|"Standard"|"Premium"|"Deluxe") {
  const labels={hi:{Basic:"बेसिक",Standard:"स्टैंडर्ड",Premium:"प्रीमियम",Deluxe:"डीलक्स"},ur:{Basic:"بیسک",Standard:"اسٹینڈرڈ",Premium:"پریمیم",Deluxe:"ڈیلکس"}};
  return locale==="hi"?labels.hi[tier]:locale==="ur"?labels.ur[tier]:tier;
}
